# Generated by Django 4.2.11 on 2024-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game_platform',
            field=models.CharField(choices=[('console', 'Console'), ('mobile', 'Mobile'), ('pc', 'PC')], default='action', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='game_genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('mmo', 'MMO'), ('puzzle', 'Puzzle'), ('role-playing', 'Role-playing'), ('simulation', 'Simulation'), ('strategy', 'Strategy'), ('sports', 'Sports')], default='action', max_length=32),
        ),
    ]
